### PR TITLE
update travis configs

### PR DESCRIPTION
**Pull request by ahussein**
Update travis config to allow:
- Install JS on a docker image
- Run coverage and unit tests for zerorobot

Installing js on the host doesnt work since the host is using python 3.4 on the host and 3.5 on a virtualenv. eventually our JS packages end up using the 3.4 system python which does not support the async/await syntax.

### CODE REVIEW

**Comment by zaibon** [comment]
>  since the host is using python 3.4 

How is that possible cause in the .travis.yml file explicitly specify python 3.5. Also from the [travis logs](https://travis-ci.org/Jumpscale/zerorobot/builds/308961562#L440), it seems the host is running python 3.5.3.

So we need to figure this out. I don't want to have to go trough a docker, this is going to extend the execution time of the script too much.

**Comment by ahussein** [comment]
According to travis docs, you get a virtualenv with the target python version which is 3.5 in our case. But on the system, the python 3 version is 3.4. You can see from the errors that eventually we end up using the system python version not the virtualenv one.
`
Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/opt/code/github/jumpscale/core9/setup.py", line 97, in <module>
        'cmds/js9_docs',
      File "/usr/lib/python3.4/site-packages/setuptools/__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.4/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.4/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.4/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
`

**Comment by zaibon** [comment]
ok, but how are we supposed to write the .travis.yml to use python3.5 then ? I don't believe we have to go to docker to solve this.

**Comment by ahussein** [comment]
We can just install the desired python version on the system ourselves as part of the prepare script. I will try to do that and see how much time it will save us.

**Comment by zaibon** [comment]
> We can just install the desired python version on the system ourselves 

No. Travis supports python3.5. I don't want us to hack on top. There is a way to just use the python from the travis host.

**Comment by zaibon** [comment]
will be done in #13 
I re-use some part of your config

**Pull request closed without merging**
